### ISSUE TITLE
Compatibility with Citizens 2 (denizen)

### ISSUE THREAD

**Issue by Tonysp** [alkarinv/BattleTracker#10]
If i create npc with Denizen trait, make him vulnerable and kill him, i got this error.

> 11:49:25 [SEVERE] Could not pass event EntityDeathEvent to BattleTracker v2.4.1.5
> org.bukkit.event.EventException
> at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
> at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
> at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
> at net.aufdemrand.denizen.npc.traits.HealthTrait.die(HealthTrait.java:209)
> at net.aufdemrand.denizen.npc.traits.HealthTrait$1.run(HealthTrait.java:290)
> at org.bukkit.craftbukkit.v1_5_R2.scheduler.CraftTask.run(CraftTask.java:53)
> at org.bukkit.craftbukkit.v1_5_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
> at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:510)
> at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:225)
> at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:474)
> at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:407)
> at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
> Caused by: java.lang.ClassCastException: org.bukkit.event.entity.EntityDeathEvent cannot be cast to org.bukkit.event.entity.PlayerDeathEvent
> at mc.alk.tracker.listeners.BTEntityListener.ede(BTEntityListener.java:154)
> at mc.alk.tracker.listeners.BTEntityListener.onEntityDeath(BTEntityListener.java:75)
> at sun.reflect.GeneratedMethodAccessor351.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:601)
> at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
> ... 12 more

**Comment by alkarinv** [comment]
Alright, I'll get a fix for this incompatibility with citizens 2.  Should be less than a day or so.
